exports.program = require('commander')
exports.inquirer = require('inquirer')
exports.ora = require('ora')
exports.chalk = require('chalk')
exports.fs = require('fs')
exports.download = require('download-git-repo')
exports.handlebars = require('handlebars')
exports.symbols = require('log-symbols')